{% set name = "wabisabi" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d3655926cd1360add5ca7301310b9fee18fa49537c68e1291e2525ae34b2b4e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - packaging

test:
  imports:
    - wabisabi

about:
  home: https://github.com/hmaarrfk/wabisabi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Deprecate your code effortlessly with decorators. Give useful warnings and docstrings for different deprecations.'

  # The remaining entries in this section are optional, but recommended
  description: |
    Breaking things is important! Breaking other's things is just mean!

    The goal of deprecations is to warn other library writers that their code
    is about to break so you can keep making agressive changes to your own.

extra:
  recipe-maintainers:
    - hmaarrfk
